# -*- coding: utf-8 -*-
"""datu-tipi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1czL2wB-Ucyfgb7E5zTWMBil63s44BGof
"""

dict={"list":[111,222,333], "tuple":(111,222,'test'), "dict":{"apple":"abols"}, "int":123, "float":3.14, "str":"teksts", "complex":3+0j, "bytes":b"test", "set":{"test","test2"}}
print("Visi datu tipi")
print(dict)

print("--------------------------------------")
print("List")
print(dict["list"])
print(type(dict["list"]))
print()
print("Tuple")
print(dict["tuple"])
print(type(dict["tuple"]))
print()
print("Dictionary")
print(dict["dict"])
print(type(dict["dict"]))
print()
print("Integer")
print(dict["int"])
print(type(dict["int"]))
print()
print("Float")
print(dict["float"])
print(type(dict["float"]))
print()
print("Strings")
print(dict["str"])
print(type(dict["str"]))
print()
print("Complex")
print(dict["complex"])
print(type(dict["complex"]))
print()
print("Bytes")
print(dict["bytes"])
print(type(dict["bytes"]))
print()
print("Sets")
print(dict["set"])
print(type(dict["set"]))
