# -*- coding: utf-8 -*-
"""pascal_tri.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WbyjYSTluxmBYRQAFYRwRbexe821TK-j
"""

n=10                #row skaits
a=[]                #a ir liste

for i in range(n):  #Izveido cik row bus
    a.append([])    
    a[i].append(1)  

    for j in range(1,i):                      #Izveido pascal tri listes formata
        a[i].append(a[i-1][j-1]+a[i-1][j])    
    if(n!=0):
        a[i].append(1)
        
    #print(a) #lai redzetu a listi

for i in range(n):                                    #Izveido Front-end pascal tri listej
    print("   "*(n-i),end="",sep="")

    for j in range(0,i+1):
        print('{0:8}'.format(a[i][j]),end="",sep="")

    print()